version: "3"
services:
  cryptoscamdb:
    container_name: cryptoscamdb
    restart: unless-stopped
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - DEBUG=*